Handle file access exception while looking for plugins
linuxdeploy/linuxdeploy pull request #242
Opened 2023-02-14 15:36 UTC by nicolas-f

My linux antivirus is raising an exception if you try to retrieve filesystem data on its binary:

/usr/bin/sentinelctl

So I updated the code to handle FileSystem exception while looking for pluings in PATH.

2023-02-14 15:37 UTC, nicolas-f commented
About #241

2023-02-14 16:18 UTC, TheAssassin requested changes
Please see my comments.

Do we really have to wrap so much code? I assume the exception occurs in the first few lines of probing code.

2023-02-14 16:18 UTC, TheAssassin commented on src/plugin/plugin.cpp
> +                    ldLog() << LD_WARNING
Should be `LD_DEBUG`, I guess. Please fix the indentation to match the other code.

2023-02-14 16:18 UTC, TheAssassin commented on src/plugin/plugin.cpp
> +                    << "Got file system error while looking for plugins :  " << ex.what() << '\n'
Please use `std::endl`.

2023-02-15 08:09 UTC, nicolas-f commented
I reduce it and can't reduce it further. The exception is raised even in the call of fs::is_directory

Thanks

2023-02-15 12:17 UTC, TheAssassin commented on src/plugin/plugin.cpp
> +
Please clean up this whitespace. Otherwise, this can be merged.

2023-02-15 13:26 UTC, TheAssassin approved these changes

2023-02-15 13:44 UTC, TheAssassin commented
Build failure is unrelated to your changes. Merging. Thanks!

2023-02-15 13:44 UTC, merged